# Book settings
title: Neural Process Family
author: Yann Dubois
logo: logo.png
exclude_patterns: ["*ConvCNP.ipynb","*ConvLNP.ipynb"]  # Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")

latex:
  latex_documents:
    targetname: book.tex

html:
  extra_navbar: ""  # Will be displayed underneath the left navbar.
